exp_name: example_high_res
batch_size: 1
num_steps: 50
start_step: 0
out_path: out/
seed: 10

# Optional: used in your image preprocessing function if supported
resolution: 1024

# Control style (appearance) via attention layers
share_attn_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Control structure (content) via ResNet layers
share_resnet_layers: [0, 1, 2, 3]

# Model name (make sure it matches your loaded pipeline)
model: sd  # or 'playground' for 1024px support

# Disentangled control settings
share_attn: true
share_cross_attn: true
share_query: true
share_key: true
share_value: false
use_adain: true
use_content_anchor: true
disentangle: true
resnet_mode: hidden

# Dataset annotation (JSON format)
annotation: /data/example/annotation.json

# Style strength (lower = more content preserved, higher = more style)
style_cfg_scale: 6.0

# Diffusion guidance strength (lower = more content preservation)
tau_attn: 0.8
tau_feat: 0.8
